Twitterapi
eibrahimarisoy/twitterbytwitapi pull request #1
Opened 2019-04-18 18:56 UTC by eibrahimarisoy

2019-04-19 12:26 UTC, halilkaya commented on .vscode/settings.json
> +{
`.vscode` dizinini .gitignore'a ekleyelim

2019-04-19 12:27 UTC, halilkaya commented
@eibrahimarisoy kodunda `flake8` calistirip reformatting yapsan guzel olur.

2019-04-19 12:29 UTC, halilkaya commented on app.py
> +config=json.load(open('config.json','r'))
buradaki `config.json`'in icinde hangi parametreler oldugunu bilmedigimiz icin repo'ya `config.json.example` adinda bir dosya olusturup icine key value seklinde hangi parametrelerin olmasi gerektigini yazarsan ben senin uygulamani kullanacagim zaman `config.json.example`'a bakarak bir `config.json` dosyasi yazabilirim. tabii ayni zamanda `config.json`'i da .gitignore'a ekle ki repo'da sensitive data bulunmasin.

2019-04-19 12:30 UTC, halilkaya commented on app.py
> +        hashtag=i['entities']["hashtags"]
(") ya da (') her yerde bu ikisinden yalnizca birini kullansan daha hos gorunur.

2019-04-19 12:31 UTC, halilkaya commented
`requirements.txt` dosyasi eksik.

2019-04-19 12:33 UTC, halilkaya commented
@eibrahimarisoy bir adet README yazsan guzel olur. uygulama ne is yapar, nasil calistirilir gibi konulari icerik olarak belirlersin. ornek olmasi acisindan github'da public flask app'lerinin readme'lerini inceleyebilirsin.

2019-04-19 12:36 UTC, halilkaya commented
bir de pull request'ler projenin bir parcasini yapip o parcayi tamamladiktan sonra ekipteki diger arkadaslarinin review'ine sunman icin kullanilir. dolayisiyla bir pull request acacagin zaman branch ismi, PR basligi, description'i o yaptigin ise spesifik olmalidir. ornegin bu pull request'inin basligini ve description'ini bu iste ne yaptigini anlatarak duzenle ki ben bilip ona gore review edebileyim. yorumlari duzeltirsin, ekipten approve alirsin; sonrasinda bu PR'i merge eder, bir sonraki yapacagin is icin farkli bir branch ile farkli bir PR acarsin.

2019-04-21 15:31 UTC, eibrahimarisoy commented
abi yazdığım remarkları güncelledim.
sadece README kaldı.
onunla ilgili çalışıyorum.

2019-04-24 08:43 UTC, halilkaya commented on app.py
> +key_secret = '{}:{}'.format(client_key, client_secret).encode('ascii')
Python 3.6+ kullaniyorsan format string kullanabilirsin: https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals

2019-04-24 08:43 UTC, halilkaya commented on app.py
> +import json
import'lari suradaki kurallara uygun siralayabilirsin: https://stackoverflow.com/a/20763446

2019-04-24 08:43 UTC, halilkaya commented on app.py
> +    global BEARER_TOKEN
burada `BEARER_TOKEN`'i global olarak tanimlamana gerek yok. zaten global'mis gibi kullanmaya devam edebilirsin.

2019-04-24 08:43 UTC, halilkaya commented on app.py
> +    data = {
bunun icerigini daha sonra dinamik yapacaksin, degil mi? denerken ok ama daha sonra hardcoded kalmasin.

2019-04-24 08:43 UTC, halilkaya commented on app.py
> +        tweet = Tweet(tweet_created_at=tweet_created_at, tweet_id=tweet_id,
yukarida olusturdugun variable'lari baska bir yerde kullanmadigin icin iceriklerini direkt `Tweet` objesine parametre olarak gecsen daha iyi olur.

```tweet = Tweet(tweet_created_at=item['created_at'], ...```

gibi.

2019-04-24 08:43 UTC, halilkaya commented on app.py
> +        if (item['entities']['hashtags']):
```if (item['entities']['hashtags']):```
yerine parantesiz
```if item['entities']['hashtags']:```
kullanabilirsin

2019-04-24 08:43 UTC, halilkaya commented on app.py
> +        if (item['entities']['urls']):
^

2019-04-24 08:43 UTC, halilkaya commented on requirements.txt
> +Flask
buraya library'leri version'lariyla birlikte yazabilirsin.
```Flask==1.0.2
...
...```
gibi

2019-04-24 08:44 UTC, halilkaya commented
Bir de `logging` kullansan guzel olur. Uygulamanin akisindaki log'lanmasi gereken seyleri duzgun bir sekilde log'layip bunu daha sonra farkli stream'lere yollayabilirsin.

2019-04-28 15:06 UTC, eibrahimarisoy commented on app.py
> +    global BEARER_TOKEN
abi dediğin şekilde kullandığımda hata aldım

2019-04-28 15:14 UTC, eibrahimarisoy commented
halil abi commentleri düzenlemeye çalıştım.
sadece harcoded kalmasın dediğin yeri tam olarak anlamadım.
temel seviye logging işlemi yapıyorum.
format string kullandım.
requirement.txt içerisine versiyon bilgilerini ekledim.

2019-04-29 10:42 UTC, aybuke commented
> sadece harcoded kalmasın dediğin yeri tam olarak anlamadım.

Bu kisimda aslinda halil in demeye calistigi, kod icersinde data dict inde value larin sabit olarak deger almamalari gerektigi. mesela until degerindeki tarih hardcoded ya da q value'su icin istanbul hardcoded. Kodu test ederken tabiki boyle deneyebilirsin :)

2019-04-30 07:27 UTC, halilkaya commented on app.py
> +    global BEARER_TOKEN
kodu cekip calistirmadim ama hata almaman lazim. nedir hata?

2019-04-30 07:31 UTC, halilkaya commented on app.py
> +        tweet_id = item['id_str']
bu satirin ustunde bosluk olmamali PEP'e gore.

bir de for loop'unun icini method'lara bolebilirsin. daha okunabilir olur.

2019-04-30 07:31 UTC, halilkaya commented on app.py
> +                hashtags = Tweet_Hashtag(tweet_id=tweet_id, hashtags=hashtag)
burada da ayni sekilde `hashtag` degiskenini olusturmadan direkt `i['text']` kullanabilirsin.

2019-04-30 07:31 UTC, halilkaya commented on app.py
> +                urls = Tweet_Url(tweet_id=tweet_id, url=url, expanded_url=expanded_url,
^

2019-04-30 07:32 UTC, halilkaya commented
@eibrahimarisoy ufak tefek eksiklikler disinda oldukca guzel olmus, eline saglik. 👏

2019-05-04 15:04 UTC, mastizada commented on .gitignore
> +.vscode/*
Github'da repository oluştururken gitignore dosyasını dile göre seçme imkanı oluyor.
Github'ın kullandığı template: [https://github.com/github/gitignore/blob/master/Python.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore)

2019-05-04 15:04 UTC, mastizada commented on app.py
> +config = json.load(open('config.json', 'r'))
Dosyaya alternatif olarak dotenv yöntemini de bilmende fayda olur:
Flask'e özel: https://github.com/grauwoelfchen/flask-dotenv/
Genel python: https://pypi.org/project/python-dotenv/

2019-05-04 15:04 UTC, mastizada commented on app.py
> +    data = {
Event, özellikle de tarih olan kısmı)

2019-05-04 15:04 UTC, mastizada commented on requirements.txt
> +postgresql postgresql-contrib
böyle bir kütüphane yok, PostgreSQL için `psycopg2-binary` paketini kullan.

2019-05-04 15:04 UTC, mastizada commented on requirements.txt
> +json
json ve base64 paketleri python'da built-in, yani sonradan kurulmuyor. Requirements dosyası kurulması gereken diger paketleri listelemek icin.

2019-05-05 23:36 UTC, eibrahimarisoy commented on .gitignore
> +.vscode/*
çok basit soru olacak ama bu template'i direkt olarak kullanarak dosya adlarını tek tek yazmak zorunda kalmayacağım sanırım

2019-05-17 21:07 UTC, mastizada commented on .gitignore
> +.vscode/*
Aynen, bu liste python'da genel olarak kullanılan tüm ignore edilmesi gereken dosyaları gösterir. Ama yine de eksikler olabilir. Mesela config.json projeye özel bir dosya, bunu elle eklemek gerekir. Ama .env hazırda oluyor.

2019-05-17 21:10 UTC, mastizada requested changes

2019-05-17 21:10 UTC, mastizada commented on .gitignore
> +.pyre/
vscode klasorunu manual olarak ekle, editör ve ide'lerin klasörleri default gelmiyor. Mesela PyCharm kullanacağın zaman .idea klasörünü eklemek gerekiyor.

2019-05-17 21:13 UTC, mastizada requested changes

2019-05-17 21:13 UTC, mastizada commented on app.py
> +                               until='2019-05-06')
Burda da tarih direkt yazilmis. Tarih verisi nereden gelmeli? Eğer bu günü göstermek istiyorsan:
```
from datetime import date
today = date.today()
str(today)
```

2019-05-17 21:20 UTC, eibrahimarisoy commented on .gitignore
> +.vscode/*
anladım abi tamamdır. söylediğin gibi .env kullnıyorum.

2019-05-17 21:23 UTC, eibrahimarisoy commented on app.py
> +                               until='2019-05-06')
porjenin akışında tarih bilgisi kullanıcıdan alınacak ama default yukardaki yapacam abi

2019-05-29 11:44 UTC, aybuke commented on app.py
> +        if not user:
bu kisimda alt alta 2 if yazmak yerine if not user or not user.verify_password(request.json.get("password")): seklinde yazabilirsin cunku if icerisinde yaptirmak istedigin ayni islem.

2019-05-29 11:44 UTC, aybuke commented on app.py
> +        if not user:
burada da if not token ile ayni islem oluyor if icerisinde daha guzel gorunmesi acisindan ayni if icinde or baglaci kullanilabilir.

2019-05-29 11:44 UTC, aybuke commented on app.py
> +def get_tweet_from_db(id):
burada parametre olarak kullanilan "id" built-in isim. Built-in kullaniyorsak sorun yok ama kullanmiyorsak parametre adini degistirirsek daha guzel olur.

2019-05-29 21:46 UTC, eibrahimarisoy commented on app.py
> +def get_tweet_from_db(id):
id yi tweetid  olarak değiştirdim.

2019-05-30 23:29 UTC, eibrahimarisoy commented
caching ve pagination yapmaya çalıştım ama pagination yaptığım url de cache mekanizmasını kullanamıyorum.

2019-09-30 00:32 UTC, mastizada requested changes

2019-09-30 00:32 UTC, mastizada commented on app.py
> +    admin = db.Column(db.Boolean)
Genelde bu tür boolean değerlerde başına "is_" koyulur. Mesela: "is_staff", "is_superuser", "is_admin" gibi.

2019-09-30 00:34 UTC, mastizada commented
Uygulama çok büyümüş, bu tür uzun işlerde Blueprint kullanmak güzel oluyor:
https://flask.palletsprojects.com/en/1.1.x/tutorial/views/

2022-10-07 12:14 UTC, closed without merging